In [1]:
!pip install python-dotenv

In [2]:
#Carregar bibliotecas

In [3]:
import pandas as pd
from dotenv import load_dotenv
import os

In [4]:
#Carregar arquivos financeiros

In [5]:
load_dotenv()
financeiro = os.getenv("PASTA_FINANCEIRO")
marketing = os.getenv("PASTA_MARKETING")
pedidos = os.getenv("PASTA_PEDIDOS")
redes_sociais = os.getenv("PASTA_REDESSOCIAIS")

In [6]:
#Carregar dados

In [7]:
planilhas_financeiro = [os.path.join(financeiro, arquivo)for arquivo in os.listdir(financeiro)]
planilhas_marketing = [os.path.join(marketing, arquivo)for arquivo in os.listdir(marketing)]
planilhas_pedidos = [os.path.join(pedidos, arquivo)for arquivo in os.listdir(pedidos)]
planilhas_redessociais = [os.path.join(redes_sociais, arquivo)for arquivo in os.listdir(redes_sociais)]

In [8]:
#Criar planilha consolidada de dados financeiros

In [9]:
consol_financeiro = pd.DataFrame()

In [10]:
for arquivo in planilhas_financeiro:
    df = pd.read_excel(arquivo)
    consol_financeiro = pd.concat([consol_financeiro, df])
#consol_financeiro.head()

,Data,Tipo,Categoria,CentroCusto,Descricao,PedidoID,FormaPagamento,Valor,FornecedorOrigem,Observacao
0,2022-03-01 11:04:00,Receita,Salão,Vendas,Recebimento pedido 22030815,22030815.0,Crédito,40.48,Sistema PDV,NaN
1,2022-03-01 12:57:00,Receita,Salão,Vendas,Recebimento pedido 22030033,22030033.0,Débito,57.01,Sistema PDV,NaN
2,2022-03-01 13:02:00,Receita,Delivery,Vendas,Recebimento pedido 22030314,22030314.0,Débito,44.29,WhatsApp,NaN
3,2022-03-01 13:11:00,Receita,Delivery,Vendas,Recebimento pedido 22030649,22030649.0,PIX,13.04,iFood,NaN
4,2022-03-01 13:25:00,Receita,Salão,Vendas,Recebimento pedido 22030857,22030857.0,Débito,163.00,Sistema PDV,NaN

In [11]:
consol_marketing = pd.DataFrame()

In [12]:
for arquivo in planilhas_marketing:
    df= pd.read_excel(arquivo)
    consol_marketing = pd.concat([consol_marketing,df])
#consol_marketing.head()

,CampanhaID,DataInicio,DataFim,NomeCampanha,Plataforma,Objetivo,Investimento,Impressoes,Cliques,LeadsCupom,Cupom,LiftEstimado
0,CMP_ANIV_202203_05,2022-03-08 00:00:00,2022-03-15 00:00:00,Aniversário da Casa,Facebook Ads,Engajamento,927.84,53720,1482,229,ANIV22035,0.1
1,CMP_ANIV_202203_01,2022-03-10 00:00:00,2022-03-18 00:00:00,Aniversário da Casa,Google Ads,Tráfego WhatsApp,682.31,61166,2354,249,ANIV22031,0.1
2,CMP_ANIV_202203_04,2022-03-15 00:00:00,2022-03-21 00:00:00,Aniversário da Casa,TikTok Ads,Alcance,1167.17,78977,2673,302,ANIV22034,0.1
3,CMP_ANIV_202203_03,2022-03-16 00:00:00,2022-03-26 00:00:00,Aniversário da Casa,Influenciador Local,Pedidos no app,872.37,69896,1643,227,ANIV22033,0.1
4,CMP_ANIV_202203_02,2022-03-18 00:00:00,2022-03-30 00:00:00,Aniversário da Casa,Influenciador Local,Pedidos no app,817.24,42392,656,55,ANIV22032,0.1

In [13]:
#Criar DB com dados consolidados e tratados para consultas em SQL

In [14]:
consol_pedidos = pd.DataFrame()

In [15]:
for arquivo in planilhas_pedidos:
    df= pd.read_excel(arquivo)
    consol_pedidos = pd.concat([consol_pedidos, df])
#consol_pedidos.head()

,PedidoID,ItemID,DataHora,ClienteID,Canal,Plataforma,Bairro,ProdutoID,Produto,CategoriaProduto,...,ValorUnitario,ValorBruto,Desconto,ValorLiquido,TaxaEntrega,FormaPagamento,StatusPedido,Cupom,CampanhaID,Observacao
0,22030815,22030815-1,2022-03-01 11:04:00,CLI02110,Salão,Balcão,NaN,P004,Burger BBQ,Burger,...,44.00,44.00,3.52,40.48,0.00,Crédito,Concluído,ANIV22033,CMP_ANIV_202203_01,NaN
1,22030033,22030033-1,2022-03-01 12:57:00,CLI03200,Salão,Balcão,NaN,P002,Smash Bacon,Burger,...,35.22,35.22,0.00,35.22,0.00,Débito,Concluído,NaN,NaN,NaN
2,22030033,22030033-2,2022-03-01 12:57:00,CLI03200,Salão,Balcão,NaN,P013,Milk Shake,Sobremesa,...,21.79,21.79,0.00,21.79,0.00,Débito,Concluído,NaN,NaN,NaN
3,22030314,22030314-1,2022-03-01 13:02:00,CLI03154,Delivery,WhatsApp,Funcionários,P002,Smash Bacon,Burger,...,35.91,35.91,0.00,35.91,8.38,Débito,Concluído,NaN,NaN,endereço incompleto
4,22030649,22030649-1,2022-03-01 13:11:00,CLI01578,Delivery,iFood,Funcionários,P011,Refrigerante Lata,Bebida,...,8.14,8.14,0.00,8.14,4.90,PIX,Concluído,NaN,NaN,NaN

In [16]:
consol_redessociais = pd.DataFrame()

In [17]:
for arquivo in planilhas_redessociais:
    df = pd.read_excel(arquivo)
    consol_redessociais = pd.concat([consol_redessociais, df])
#consol_redessociais.head()

,PostID,DataHora,Rede,TipoConteudo,Tema,Pago,CampanhaID,Alcance,Curtidas,Comentarios,Compartilhamentos,Cliques
0,POST_202203_0015,2022-03-19 15:59:00,Instagram,Story,Data comemorativa,Sim,CMP_ANIV_202203_03,8645,1063,79,145,120
1,POST_202203_0026,2022-03-01 21:58:00,Instagram,Post,Bastidores,Sim,CMP_ANIV_202203_01,34100,3005,226,590,713
2,POST_202203_0041,2022-03-02 15:09:00,Instagram,Post,Combo,Não,NaN,5384,465,33,62,58
3,POST_202203_0007,2022-03-02 16:17:00,Instagram,Reels,Delivery,Sim,CMP_ANIV_202203_05,86683,4060,158,285,1610
4,POST_202203_0038,2022-03-03 17:05:00,Instagram,Reels,Promoção,Não,NaN,1293,37,2,7,30

In [21]:
#Tratamento de dados com formatos não suportados pelo SQLite

In [22]:
def converter_tudo(df):
    for coluna in df.columns:
        df[coluna] = df[coluna].apply(lambda x: str(x) if not isinstance(x, (int, float)) else x)
    return df

consol_financeiro   = converter_tudo(consol_financeiro)
consol_marketing    = converter_tudo(consol_marketing)
consol_pedidos      = converter_tudo(consol_pedidos)
consol_redessociais = converter_tudo(consol_redessociais)

In [18]:
#Converter as planilhas em um DB em SQL para tratamento de dados

In [19]:
import sqlite3

In [23]:
# Criar/conectar ao banco
conn = sqlite3.connect("BlackBull.db")

# Salvar cada DataFrame como uma tabela
consol_financeiro.to_sql("financeiro", conn, if_exists="replace", index=False)
consol_marketing.to_sql("marketing", conn, if_exists="replace", index=False)
consol_pedidos.to_sql("pedidos", conn, if_exists="replace", index=False)
consol_redessociais.to_sql("redes_sociais", conn, if_exists="replace", index=False)

# Fechar conexão
conn.close()

print("Banco de dados criado com sucesso!")

Banco de dados criado com sucesso!

In [25]:
!jupyter nbconvert --to script Pipe_dados.ipynb
print("Arquivo criado com sucesso!")

Arquivo criado com sucesso!

[NbConvertApp] Converting notebook Pipe_dados.ipynb to script
[NbConvertApp] Writing 2596 bytes to Pipe_dados.py